
qualification_mapping = {
    1: 'Secondary Education',
    2: 'University Degree / Bachelors',
    3: 'University Degree / Bachelors',
    4: 'University Masters',
    5: 'Doctorate',
    6: 'Post-Secondary',
    9: 'Secondary Education',
    10: 'Secondary Education',
    11: 'Secondary Education',
    12: 'Secondary Education',
    13: 'Secondary Education',
    14: 'Secondary Education',
    15: 'Secondary Education',
    18: 'Secondary Education',
    19: 'Secondary Education',
    20: 'Secondary Education',
    22: 'Secondary Education',
    25: 'Secondary Education',
    26: 'Secondary Education',
    27: 'Secondary Education',
    29: 'Secondary Education',
    30: 'Secondary Education',
    31: 'Secondary Education',
    33: 'Secondary Education',
    34: 'Secondary Education',
    35: 'Secondary Education',
    36: 'Secondary Education',
    37: 'Secondary Education',
    38: 'Secondary Education',
    39: 'Post-Secondary',
    40: 'University Degree / Bachelors',
    41: 'Post-Secondary',
    42: 'Post-Secondary',
    43: 'University Masters',
    44: 'Doctorate'
}

profession_mapping = {
    0: 'Students',
    1: 'Legislative and Executive Officials, Directors and Managers',
    2: 'Specialists in Intellectual and Scientific Activities',
    3: 'Intermediate Level Technicians and Professions',
    4: 'Administrative Staff',
    5: 'Service Workers and Sales Workers',
    6: 'Agricultural, Forestry, and Fishery Workers',
    7: 'Skilled Workers in Industry, Construction, and Craftsmen',
    8: 'Machine Operators and Assembly Workers',
    9: 'Unskilled Workers',
    10: 'Armed Forces',
    90: 'Other Situations',
    99: 'Other Situations',
    101: 'Armed Forces',
    102: 'Armed Forces',
    103: 'Armed Forces',
    112: 'Legislative and Executive Officials, Directors and Managers',
    114: 'Legislative and Executive Officials, Directors and Managers',
    121: 'Specialists in Intellectual and Scientific Activities',
    122: 'Health Professionals',
    123: 'Teachers',
    124: 'Specialists in Intellectual and Scientific Activities',
    125: 'ICT Specialists',
    131: 'Science and Engineering Technicians',
    132: 'Science and Engineering Technicians',
    134: 'Legal, Social, and Cultural Technicians',
    135: 'ICT Specialists',
    141: 'Office Workers and Data Processing Operators',
    143: 'Office Workers and Data Processing Operators',
    144: 'Administrative Staff',
    151: 'Service Workers and Sales Workers',
    152: 'Sales and Service Workers',
    153: 'Sales and Service Workers',
    154: 'Service Workers and Sales Workers',
    161: 'Agricultural, Forestry, and Fishery Workers',
    163: 'Agricultural, Forestry, and Fishery Workers',
    171: 'Skilled Workers in Industry, Construction, and Craftsmen',
    172: 'Skilled Workers in Industry, Construction, and Craftsmen',
    173: 'Skilled Workers in Industry, Construction, and Craftsmen',
    174: 'Skilled Workers in Industry, Construction, and Craftsmen',
    175: 'Skilled Workers in Industry, Construction, and Craftsmen',
    181: 'Machine Operators and Assembly Workers',
    182: 'Machine Operators and Assembly Workers',
    183: 'Machine Operators and Assembly Workers',
    191: 'Unskilled Workers',
    192: 'Unskilled Workers',
    193: 'Unskilled Workers',
    194: 'Unskilled Workers',
    195: 'Unskilled Workers'
}



