
word_mapper = {
    "4 me": "for me",
    "s": "is",
    "m": "I'm",
    "ur": "you're",
    "Thanx": "thanks",
    "u": "you",
    "wan": "want",
    "4 u": "for you",
    "jus": "just",
    "re": "are",
    "2": "to",
    "4": "for",
    "lor": "!",
    "thk": "think",
    "w": "with",
    "dun": "don't",
    "smth": "something",
    "ll": "will",
    "sis": "sister",
    "dis": "this",
    "den": "then",
    "wat": "what",
    "b": "be",
    "rem": "remember",
    "msg": "message",
    "cos": "cause",
    "ve": "have",
    "aft": "after",
    "cant": "can't",
    "n": "and",
    "y": "why",
    "mus": "must",
    "gd": "good",
    "ard": "affirmation",
    "k": "ok",
    "diff": "different",
    "tmr": "tomorrow",
    "nvm": "never mind",
    "didnt": "didn't",
    "mah": "mom",
    "noe": "know",
    "c": "see",
    "wed": "wednesday",
    "e": "the",
    "abt": "about",
    "phots": "photos",
    "Ü": "you",
    "r": "are",
    "luv": "love",
    "buzy": "busy",
    "da": "the",
    "ü": "you"
}


